### ISSUE TITLE
Build fails unable to locate BusinessProvider

### ISSUE THREAD

**Issue by papyr** [whyfine/T4Project#2]
C:\users\papi\desktop\T4Project\T4Project.Demo\ControllersExt\FormulaController.cs(82,11,82,27): error CS0103: The name 'BusinessProvider' does not exist in the current context

Also the ControllersExt folder and the namespace of the classes are colliding and creating errors, because they're not the same

**Comment by ten-nen** [comment]
@papyr 
This is a CRUD class that comes from another project
Since this is a t4 demo, there is no introduction to it
reference:https://github.com/whyfine/SimpleLayer/blob/master/Business/BusinessProvider.cs

**Comment by whyfine** [comment]
@papyr

**Comment by papyr** [comment]
Hi, T4 is still not building, should I reference the entire simplelayer blob project to get it working. not sure what all I need to get this going for T4's gen

`ITemplateBll Severity  Code    Description Project File    Line    Suppression State
Error   CS0246  The type or namespace name 'ITemplateBll' could not be found (are you missing a using directive or an assembly reference?)  T4Project.Models    D:\T4Project.Models\BusinessProvider.cs 23  Active`

 getting more errors on the build

`Severity   Code    Description Project File    Line    Suppression State
Error   CS0103  The name 'BusinessProvider' does not exist in the current context   T4Project.Demo  D:\T4Project.Demo\Controllers\ConditionController.cs    52  Active`

**Comment by ten-nen** [comment]
@papyr BusinessProvider class is the BLL entry, you need to complete it
example:https://github.com/whyfine/SimpleLayer/blob/master/Business/BusinessProvider.cs
